language: r
cache: packages
sudo: false

r_packages:
  - covr
  - RPostgreSQL
r_github_packages:
  - rstats-db/RPostgres

addons:
  postgresql: "9.4"
  apt:
    packages:
      - libpq-dev

services:
  - postgresql

after_success:
  - Rscript -e 'covr::codecov()'
