language: c

sudo: required

services:
  - redis-server

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_aptget libhiredis-dev

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package ropensci/RedisAPI
  - git clone --recursive https://github.com/richfitz/rrlite && make -C rrlite install && rm -rf rrlite

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
