language: r
cache: packages
sudo: false

# NOTE: there is quite a bit of extra installation required here; this
# is to ensure that all tests can be run on travis while keeping the
# package able to go on CRAN; once redux is on CRAN it would move from
# here into Suggests.
r_packages:
  - covr
r_github_packages:
  - richfitz/redux
  - richfitz/rrlite
apt_packages:
  - libhiredis-dev
services:
  - redis-server
after_success:
  - Rscript -e 'covr::codecov()'
